CREATE TABLE IF NOT EXISTS "anpr_records" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "anpr_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"plate_wim" text,
	"plate_camera" text,
	"confidence_wim" numeric(5, 2),
	"confidence_camera" numeric(5, 2),
	"image_wim_url" text,
	"image_camera_url" text,
	"thumbnail_url" text,
	"status" text DEFAULT 'pending',
	"accuracy_percent" numeric(5, 2),
	"reviewed_by" text,
	"reviewed_at" timestamp,
	"notes" text,
	"organization_id" text
);
